/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserImport } from './routes/user'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as CompanyImport } from './routes/company'
import { Route as IndexImport } from './routes/index'
import { Route as CompanySettingImport } from './routes/company/setting'
import { Route as CompanyLoginFormImport } from './routes/company/login-form'
import { Route as CompanyAiAnalysisImport } from './routes/company/ai-analysis'
import { Route as UserSurveyIndexImport } from './routes/user/survey/index'
import { Route as UserShopIndexImport } from './routes/user/shop/index'
import { Route as CompanySurveyIndexImport } from './routes/company/survey/index'
import { Route as CompanyCustomerIndexImport } from './routes/company/customer/index'
import { Route as UserSurveyIdImport } from './routes/user/survey/$id'
import { Route as CompanySurveyCreateImport } from './routes/company/survey/create'
import { Route as CompanySurveyIdImport } from './routes/company/survey/$id'
import { Route as CompanyCustomerCreateImport } from './routes/company/customer/create'
import { Route as CompanyCustomerIdImport } from './routes/company/customer/$id'
import { Route as UserShopIdIndexImport } from './routes/user/shop/$id/index'
import { Route as UserShopIdUserUserIdImport } from './routes/user/shop/$id/user.$userId'

// Create/Update Routes

const UserRoute = UserImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CompanyRoute = CompanyImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CompanySettingRoute = CompanySettingImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => CompanyRoute,
} as any)

const CompanyLoginFormRoute = CompanyLoginFormImport.update({
  id: '/login-form',
  path: '/login-form',
  getParentRoute: () => CompanyRoute,
} as any)

const CompanyAiAnalysisRoute = CompanyAiAnalysisImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => CompanyRoute,
} as any)

const UserSurveyIndexRoute = UserSurveyIndexImport.update({
  id: '/survey/',
  path: '/survey/',
  getParentRoute: () => UserRoute,
} as any)

const UserShopIndexRoute = UserShopIndexImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => UserRoute,
} as any)

const CompanySurveyIndexRoute = CompanySurveyIndexImport.update({
  id: '/survey/',
  path: '/survey/',
  getParentRoute: () => CompanyRoute,
} as any)

const CompanyCustomerIndexRoute = CompanyCustomerIndexImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => CompanyRoute,
} as any)

const UserSurveyIdRoute = UserSurveyIdImport.update({
  id: '/survey/$id',
  path: '/survey/$id',
  getParentRoute: () => UserRoute,
} as any)

const CompanySurveyCreateRoute = CompanySurveyCreateImport.update({
  id: '/survey/create',
  path: '/survey/create',
  getParentRoute: () => CompanyRoute,
} as any)

const CompanySurveyIdRoute = CompanySurveyIdImport.update({
  id: '/survey/$id',
  path: '/survey/$id',
  getParentRoute: () => CompanyRoute,
} as any)

const CompanyCustomerCreateRoute = CompanyCustomerCreateImport.update({
  id: '/customer/create',
  path: '/customer/create',
  getParentRoute: () => CompanyRoute,
} as any)

const CompanyCustomerIdRoute = CompanyCustomerIdImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => CompanyRoute,
} as any)

const UserShopIdIndexRoute = UserShopIdIndexImport.update({
  id: '/shop/$id/',
  path: '/shop/$id/',
  getParentRoute: () => UserRoute,
} as any)

const UserShopIdUserUserIdRoute = UserShopIdUserUserIdImport.update({
  id: '/shop/$id/user/$userId',
  path: '/shop/$id/user/$userId',
  getParentRoute: () => UserRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/company/ai-analysis': {
      id: '/company/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/company/ai-analysis'
      preLoaderRoute: typeof CompanyAiAnalysisImport
      parentRoute: typeof CompanyImport
    }
    '/company/login-form': {
      id: '/company/login-form'
      path: '/login-form'
      fullPath: '/company/login-form'
      preLoaderRoute: typeof CompanyLoginFormImport
      parentRoute: typeof CompanyImport
    }
    '/company/setting': {
      id: '/company/setting'
      path: '/setting'
      fullPath: '/company/setting'
      preLoaderRoute: typeof CompanySettingImport
      parentRoute: typeof CompanyImport
    }
    '/company/customer/$id': {
      id: '/company/customer/$id'
      path: '/customer/$id'
      fullPath: '/company/customer/$id'
      preLoaderRoute: typeof CompanyCustomerIdImport
      parentRoute: typeof CompanyImport
    }
    '/company/customer/create': {
      id: '/company/customer/create'
      path: '/customer/create'
      fullPath: '/company/customer/create'
      preLoaderRoute: typeof CompanyCustomerCreateImport
      parentRoute: typeof CompanyImport
    }
    '/company/survey/$id': {
      id: '/company/survey/$id'
      path: '/survey/$id'
      fullPath: '/company/survey/$id'
      preLoaderRoute: typeof CompanySurveyIdImport
      parentRoute: typeof CompanyImport
    }
    '/company/survey/create': {
      id: '/company/survey/create'
      path: '/survey/create'
      fullPath: '/company/survey/create'
      preLoaderRoute: typeof CompanySurveyCreateImport
      parentRoute: typeof CompanyImport
    }
    '/user/survey/$id': {
      id: '/user/survey/$id'
      path: '/survey/$id'
      fullPath: '/user/survey/$id'
      preLoaderRoute: typeof UserSurveyIdImport
      parentRoute: typeof UserImport
    }
    '/company/customer/': {
      id: '/company/customer/'
      path: '/customer'
      fullPath: '/company/customer'
      preLoaderRoute: typeof CompanyCustomerIndexImport
      parentRoute: typeof CompanyImport
    }
    '/company/survey/': {
      id: '/company/survey/'
      path: '/survey'
      fullPath: '/company/survey'
      preLoaderRoute: typeof CompanySurveyIndexImport
      parentRoute: typeof CompanyImport
    }
    '/user/shop/': {
      id: '/user/shop/'
      path: '/shop'
      fullPath: '/user/shop'
      preLoaderRoute: typeof UserShopIndexImport
      parentRoute: typeof UserImport
    }
    '/user/survey/': {
      id: '/user/survey/'
      path: '/survey'
      fullPath: '/user/survey'
      preLoaderRoute: typeof UserSurveyIndexImport
      parentRoute: typeof UserImport
    }
    '/user/shop/$id/': {
      id: '/user/shop/$id/'
      path: '/shop/$id'
      fullPath: '/user/shop/$id'
      preLoaderRoute: typeof UserShopIdIndexImport
      parentRoute: typeof UserImport
    }
    '/user/shop/$id/user/$userId': {
      id: '/user/shop/$id/user/$userId'
      path: '/shop/$id/user/$userId'
      fullPath: '/user/shop/$id/user/$userId'
      preLoaderRoute: typeof UserShopIdUserUserIdImport
      parentRoute: typeof UserImport
    }
  }
}

// Create and export the route tree

interface CompanyRouteChildren {
  CompanyAiAnalysisRoute: typeof CompanyAiAnalysisRoute
  CompanyLoginFormRoute: typeof CompanyLoginFormRoute
  CompanySettingRoute: typeof CompanySettingRoute
  CompanyCustomerIdRoute: typeof CompanyCustomerIdRoute
  CompanyCustomerCreateRoute: typeof CompanyCustomerCreateRoute
  CompanySurveyIdRoute: typeof CompanySurveyIdRoute
  CompanySurveyCreateRoute: typeof CompanySurveyCreateRoute
  CompanyCustomerIndexRoute: typeof CompanyCustomerIndexRoute
  CompanySurveyIndexRoute: typeof CompanySurveyIndexRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyAiAnalysisRoute: CompanyAiAnalysisRoute,
  CompanyLoginFormRoute: CompanyLoginFormRoute,
  CompanySettingRoute: CompanySettingRoute,
  CompanyCustomerIdRoute: CompanyCustomerIdRoute,
  CompanyCustomerCreateRoute: CompanyCustomerCreateRoute,
  CompanySurveyIdRoute: CompanySurveyIdRoute,
  CompanySurveyCreateRoute: CompanySurveyCreateRoute,
  CompanyCustomerIndexRoute: CompanyCustomerIndexRoute,
  CompanySurveyIndexRoute: CompanySurveyIndexRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface UserRouteChildren {
  UserSurveyIdRoute: typeof UserSurveyIdRoute
  UserShopIndexRoute: typeof UserShopIndexRoute
  UserSurveyIndexRoute: typeof UserSurveyIndexRoute
  UserShopIdIndexRoute: typeof UserShopIdIndexRoute
  UserShopIdUserUserIdRoute: typeof UserShopIdUserUserIdRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserSurveyIdRoute: UserSurveyIdRoute,
  UserShopIndexRoute: UserShopIndexRoute,
  UserSurveyIndexRoute: UserSurveyIndexRoute,
  UserShopIdIndexRoute: UserShopIdIndexRoute,
  UserShopIdUserUserIdRoute: UserShopIdUserUserIdRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/company/ai-analysis': typeof CompanyAiAnalysisRoute
  '/company/login-form': typeof CompanyLoginFormRoute
  '/company/setting': typeof CompanySettingRoute
  '/company/customer/$id': typeof CompanyCustomerIdRoute
  '/company/customer/create': typeof CompanyCustomerCreateRoute
  '/company/survey/$id': typeof CompanySurveyIdRoute
  '/company/survey/create': typeof CompanySurveyCreateRoute
  '/user/survey/$id': typeof UserSurveyIdRoute
  '/company/customer': typeof CompanyCustomerIndexRoute
  '/company/survey': typeof CompanySurveyIndexRoute
  '/user/shop': typeof UserShopIndexRoute
  '/user/survey': typeof UserSurveyIndexRoute
  '/user/shop/$id': typeof UserShopIdIndexRoute
  '/user/shop/$id/user/$userId': typeof UserShopIdUserUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/company/ai-analysis': typeof CompanyAiAnalysisRoute
  '/company/login-form': typeof CompanyLoginFormRoute
  '/company/setting': typeof CompanySettingRoute
  '/company/customer/$id': typeof CompanyCustomerIdRoute
  '/company/customer/create': typeof CompanyCustomerCreateRoute
  '/company/survey/$id': typeof CompanySurveyIdRoute
  '/company/survey/create': typeof CompanySurveyCreateRoute
  '/user/survey/$id': typeof UserSurveyIdRoute
  '/company/customer': typeof CompanyCustomerIndexRoute
  '/company/survey': typeof CompanySurveyIndexRoute
  '/user/shop': typeof UserShopIndexRoute
  '/user/survey': typeof UserSurveyIndexRoute
  '/user/shop/$id': typeof UserShopIdIndexRoute
  '/user/shop/$id/user/$userId': typeof UserShopIdUserUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/company/ai-analysis': typeof CompanyAiAnalysisRoute
  '/company/login-form': typeof CompanyLoginFormRoute
  '/company/setting': typeof CompanySettingRoute
  '/company/customer/$id': typeof CompanyCustomerIdRoute
  '/company/customer/create': typeof CompanyCustomerCreateRoute
  '/company/survey/$id': typeof CompanySurveyIdRoute
  '/company/survey/create': typeof CompanySurveyCreateRoute
  '/user/survey/$id': typeof UserSurveyIdRoute
  '/company/customer/': typeof CompanyCustomerIndexRoute
  '/company/survey/': typeof CompanySurveyIndexRoute
  '/user/shop/': typeof UserShopIndexRoute
  '/user/survey/': typeof UserSurveyIndexRoute
  '/user/shop/$id/': typeof UserShopIdIndexRoute
  '/user/shop/$id/user/$userId': typeof UserShopIdUserUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/login'
    | '/register'
    | '/user'
    | '/company/ai-analysis'
    | '/company/login-form'
    | '/company/setting'
    | '/company/customer/$id'
    | '/company/customer/create'
    | '/company/survey/$id'
    | '/company/survey/create'
    | '/user/survey/$id'
    | '/company/customer'
    | '/company/survey'
    | '/user/shop'
    | '/user/survey'
    | '/user/shop/$id'
    | '/user/shop/$id/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/login'
    | '/register'
    | '/user'
    | '/company/ai-analysis'
    | '/company/login-form'
    | '/company/setting'
    | '/company/customer/$id'
    | '/company/customer/create'
    | '/company/survey/$id'
    | '/company/survey/create'
    | '/user/survey/$id'
    | '/company/customer'
    | '/company/survey'
    | '/user/shop'
    | '/user/survey'
    | '/user/shop/$id'
    | '/user/shop/$id/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/login'
    | '/register'
    | '/user'
    | '/company/ai-analysis'
    | '/company/login-form'
    | '/company/setting'
    | '/company/customer/$id'
    | '/company/customer/create'
    | '/company/survey/$id'
    | '/company/survey/create'
    | '/user/survey/$id'
    | '/company/customer/'
    | '/company/survey/'
    | '/user/shop/'
    | '/user/survey/'
    | '/user/shop/$id/'
    | '/user/shop/$id/user/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UserRoute: typeof UserRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UserRoute: UserRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/company",
        "/login",
        "/register",
        "/user"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/company": {
      "filePath": "company.tsx",
      "children": [
        "/company/ai-analysis",
        "/company/login-form",
        "/company/setting",
        "/company/customer/$id",
        "/company/customer/create",
        "/company/survey/$id",
        "/company/survey/create",
        "/company/customer/",
        "/company/survey/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/user": {
      "filePath": "user.tsx",
      "children": [
        "/user/survey/$id",
        "/user/shop/",
        "/user/survey/",
        "/user/shop/$id/",
        "/user/shop/$id/user/$userId"
      ]
    },
    "/company/ai-analysis": {
      "filePath": "company/ai-analysis.tsx",
      "parent": "/company"
    },
    "/company/login-form": {
      "filePath": "company/login-form.tsx",
      "parent": "/company"
    },
    "/company/setting": {
      "filePath": "company/setting.tsx",
      "parent": "/company"
    },
    "/company/customer/$id": {
      "filePath": "company/customer/$id.tsx",
      "parent": "/company"
    },
    "/company/customer/create": {
      "filePath": "company/customer/create.tsx",
      "parent": "/company"
    },
    "/company/survey/$id": {
      "filePath": "company/survey/$id.tsx",
      "parent": "/company"
    },
    "/company/survey/create": {
      "filePath": "company/survey/create.tsx",
      "parent": "/company"
    },
    "/user/survey/$id": {
      "filePath": "user/survey/$id.tsx",
      "parent": "/user"
    },
    "/company/customer/": {
      "filePath": "company/customer/index.tsx",
      "parent": "/company"
    },
    "/company/survey/": {
      "filePath": "company/survey/index.tsx",
      "parent": "/company"
    },
    "/user/shop/": {
      "filePath": "user/shop/index.tsx",
      "parent": "/user"
    },
    "/user/survey/": {
      "filePath": "user/survey/index.tsx",
      "parent": "/user"
    },
    "/user/shop/$id/": {
      "filePath": "user/shop/$id/index.tsx",
      "parent": "/user"
    },
    "/user/shop/$id/user/$userId": {
      "filePath": "user/shop/$id/user.$userId.tsx",
      "parent": "/user"
    }
  }
}
ROUTE_MANIFEST_END */
